### ISSUE TITLE
Content: Prim Algorithm

### ISSUE THREAD

**Issue by HarshCasper** [TesseractCoding/NeoAlgo-Docs#103]
## Description

Add the article for Prim algorithm. Use the following structure: 
- Introduction
- Explanation
- Algorithm
- Code
- Sample I/O
- Complexity Analysis

**Comment by Inventor77** [comment]
@HarshCasper   I would love to work in this Issue Please Assign this to me

**Comment by Amit366** [comment]
@HarshCasper can I work?
