### ISSUE TITLE
Content: Knuth–Morris–Pratt Algorithm

### ISSUE THREAD

**Issue by HarshCasper** [TesseractCoding/NeoAlgo-Docs#106]
## Description

Add the article for Knuth–Morris–Pratt Algorithm. Use the following structure: 
- Introduction
- Explanation
- Algorithm
- Code
- Sample I/O
- Complexity Analysis

**Comment by HeroicHitesh** [comment]
@HarshCasper I would like to work on this

**Comment by HarshCasper** [comment]
> @HarshCasper I would like to work on this

Great to see you again @HeroicHitesh :100: 

Are you participating in GSSoC?

**Comment by HeroicHitesh** [comment]
> Great to see you again @HeroicHitesh 💯

Thanks and same here 
> Are you participating in GSSoC?

Yes.
