### ISSUE TITLE
Content: Strongly Connected Components - Tarjan's Algorithm

### ISSUE THREAD

**Issue by HarshCasper** [TesseractCoding/NeoAlgo-Docs#115]
## Description

Add the article for Strongly Connected Components - Tarjan's Algorithm. Use the following structure: 
- Introduction
- Explanation
- Algorithm
- Code
- Sample I/O
- Complexity Analysis

**Comment by AshuKV** [comment]
Can I work on this issue under GSSOC21? Kindly assign it to me.
