### ISSUE TITLE
CI: Add LightHouse CI and Bot to the Website

### ISSUE THREAD

**Issue by HarshCasper** [TesseractCoding/NeoAlgo-Docs#117]
## Description

Add LightHouse CI to the Website and create a Bot that can paste the LightHouse CI results as a PR comment. 

These are few things that would prove useful: 

- https://github.com/UnlyEd/github-action-await-vercel
- https://github.com/treosh/lighthouse-ci-action
- https://github.com/marocchino/sticky-pull-request-comment

We need these data to be automatically added over the PR: 

- Performance
- Accessibility
- Best Practices
- SEO
- PWA

**Comment by AshuKV** [comment]
Can I work on this issue under GSSOC21? Kindly assign it to me.
