### ISSUE TITLE
Content: Add to data structures

### ISSUE THREAD

**Issue by ShambhaviSharma0110** [TesseractCoding/NeoAlgo-Docs#119]
## 📚 Documentation

I would like to add some content for data structures.
What are data structures and why we need them
Types of data structures
Time complexities
Applications

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes!

**Comment by HarshCasper** [comment]
> ## 📚 Documentation
> I would like to add some content for data structures.
> What are data structures and why we need them
> Types of data structures
> Time complexities
> Applications
> 
> ### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
> Yes!

It is already in progress.
