### ISSUE TITLE
Navigation on smaller screen

### ISSUE THREAD

**Issue by satcasm** [TesseractCoding/NeoAlgo-Docs#133]
The toggle between dark and light mode , will look better if we keep it on the navbar itself. 
As of now we need to click the hamburger icon then it appears.
Also the width seems to be a bit much would propose to reduce it a bit.
Would like to work on in under GSSOC' 21 ,if seemed necessary.
Thanks!

Screenshot Reference:
![image](https://user-images.githubusercontent.com/56315878/114214565-16aa7480-9982-11eb-9fbd-a2be7905be28.png)

**Comment by HarshCasper** [comment]
Thanks for taking this up! I'm not so sure about how much freedom Docusaurus would provide in this regard but you can surely experiment. We might change the label to `level3` after we see the implementation.

**Comment by satcasm** [comment]
Hey @HarshCasper , it seems that Docusaurus gives freedom just for the theme manipulation, positioning of elements can't be done . Tho, I have reduced the width of the navbar for smaller devices. Should I make a PR with just that ?

Screenshot Reference:
![image](https://user-images.githubusercontent.com/56315878/114276506-897c2400-9a44-11eb-9d76-650b3d356ca0.png)

**Comment by HarshCasper** [comment]
> Hey @HarshCasper , it seems that Docusaurus gives freedom just for the theme manipulation, positioning of elements can't be done . Tho, I have reduced the width of the navbar for smaller devices. Should I make a PR with just that ?
> 
> Screenshot Reference:
> ![image](https://user-images.githubusercontent.com/56315878/114276506-897c2400-9a44-11eb-9d76-650b3d356ca0.png)

For sure.
