### ISSUE TITLE
Content: What are Sorting Algorithms?

### ISSUE THREAD

**Issue by HarshCasper** [TesseractCoding/NeoAlgo-Docs#14]
## Description 

Add the article for `What are Sorting Algorithms`. The basic layout for the article should be: 

- Introduction to Sorting
- What are Sorting Algorithms? 
- Popular Sorting Algorithms 
- Comparison of these algorithms 

This article should be between 500-700 words in length. You should use traditional Markdown to prepare the content and the use of external images is prohibited. You can however create your own images. Run a proper Grammarly Lint check before submitting the PR.

**Comment by rohanbabbar04** [comment]
@HarshCasper I would like to work on this issue
Do assign me this issue

**Comment by HarshCasper** [comment]
Hi @rohanbabbar04 

Thanks for taking this up! I hope you spend some time in understanding the directory structure and where to make the PR. If you are confused, check it right here: https://github.com/TesseractCoding/NeoAlgo-Docs/tree/main/docs/sorting-algorithms

I have already created a file for you named `sorting-algorithms.md`. And I have added the same on the sidebar. So I guess you will have a fair understanding of how to contribute (which is much different from NeoAlgo)

**Comment by HarshCasper** [comment]
Heya - Hope you are working on this ✨  

We have just pushed some new features on the `main` so it would be great if you can pull the changes from the `main` branch, so that we don't run into any merge conflicts. 

Second, I have some important notes for you. While adding the articles, it would be preferred if you use the `mdx` file extension instead of `md`. `mdx` provides us to combine Markdown + React. And we will be using it for a good reason. 

First, we want to tab the codes like these: 

![image](https://user-images.githubusercontent.com/47351025/114029857-94458600-9897-11eb-99cf-a1a576301732.png)

Using standard markdown won't be beneficial for us. We can use some React Code to make it possible. Don't fret out if you don't know React. Here is an official [documentation](https://docusaurus.io/docs/markdown-features/code-blocks#multi-language-support-code-blocks) that you can refer to format the Code in separate tabs. Have a look and let me know if you are still in trouble. 

Also try to keep the I/O samples same for both the Code. If it requires minor altercations, feel free to do them. Thanks!

**Comment by Saatvik21** [comment]
@rohanbabbar04 are you still working on this? 

If not @HarshCasper can you assign me this issue as it's over 10 days.

**Comment by rohanbabbar04** [comment]
@Saatvik21 you can work on it as I am under quarantine I'll unassign myself

**Comment by HarshCasper** [comment]
> @Saatvik21 you can work on it as I am under quarantine I'll unassign myself

Please take care!

**Comment by HarshCasper** [comment]
@Saatvik21 As a goodwill gesture, please keep the issue unassigned for now. @rohanbabbar04 has been a valuable contributor and we don't wish to show him as someone replaceable with time and condition. He can take it up once he comes back healthy and fine and we would love to have him contribute.

**Comment by Saatvik21** [comment]
> @Saatvik21 As a goodwill gesture, please keep the issue unassigned for now. @rohanbabbar04 has been a valuable contributor and we don't wish to show him as someone replaceable with time and condition. He can take it up once he comes back healthy and fine and we would love to have him contribute.

Yeah sure, I didn't know that sorry about that. @rohanbabbar04 Take care man! 🙏
