### ISSUE TITLE
Perfect number

### ISSUE THREAD

**Issue by Amit366** [TesseractCoding/NeoAlgo-Docs#142]
## 📚 Documentation

Article for perfect numbers. 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

**Comment by Harikrishnan6336** [comment]
This issue is already assigned to me [here](https://github.com/TesseractCoding/NeoAlgo-Docs/issues/122) @HarshCasper 

Kindly Check the existing issues before opening new issues.
