### ISSUE TITLE
Documentation for preorder inorder and postorder tree traversals

### ISSUE THREAD

**Issue by aaadddiii** [TesseractCoding/NeoAlgo-Docs#151]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

documentation for preorder,inorder , postorder traversal

## Pitch

documentation for preorder,inorder , postorder traversal

**Comment by HarshCasper** [comment]
It's already a part now with the Binary Tree article.
