### ISSUE TITLE
Content: What are Data Structures

### ISSUE THREAD

**Issue by HarshCasper** [TesseractCoding/NeoAlgo-Docs#16]
## Description 

Add the article for `What are Data Structures`. The basic layout for the article should be: 

- Introduction to Data Structures
- Types of Data Structures
- Major Operations in Data Structures
- Advantages of Data Structures

This article should be between 500-700 words in length. You should use traditional Markdown to prepare the content and the use of external images is prohibited. You can however create your own images. Run a proper Grammarly Lint check before submitting the PR.

**Comment by Saatvik21** [comment]
I would like to work on this issue.

**Comment by HarshCasper** [comment]
Hi @Saatvik21 

Thanks for taking this up! I hope you spend some time in understanding the directory structure and where to make the PR. If you are confused, check it right here: https://github.com/TesseractCoding/NeoAlgo-Docs/tree/main/docs/data-structures

I have already created a file for you named `data-structures.md`. And I have added the same on the sidebar. So I guess you will have a fair understanding of how to contribute (which is much different from NeoAlgo)

**Comment by HarshCasper** [comment]
Heya - Hope you are working on this ✨  

We have just pushed some new features on the `main` so it would be great if you can pull the changes from the `main` branch, so that we don't run into any merge conflicts. 

Second, I have some important notes for you. While adding the articles, it would be preferred if you use the `mdx` file extension instead of `md`. `mdx` provides us to combine Markdown + React. And we will be using it for a good reason. 

First, we want to tab the codes like these: 

![image](https://user-images.githubusercontent.com/47351025/114029857-94458600-9897-11eb-99cf-a1a576301732.png)

Using standard markdown won't be beneficial for us. We can use some React Code to make it possible. Don't fret out if you don't know React. Here is an official [documentation](https://docusaurus.io/docs/markdown-features/code-blocks#multi-language-support-code-blocks) that you can refer to format the Code in separate tabs. Have a look and let me know if you are still in trouble. 

Also try to keep the I/O samples same for both the Code. If it requires minor altercations, feel free to do them. Thanks!

**Comment by Saatvik21** [comment]
@HarshCasper Hey, I've a doubt. Do I have to show code examples for the major operations in data structures or just the theory part of it?

**Comment by HarshCasper** [comment]
> @HarshCasper Hey, I've a doubt. Do I have to show code examples for the major operations in data structures or just the theory part of it?

Don't focus on any specific Data Structure. Just focus on what they are, their types, advantages and applications.
