### ISSUE TITLE
CI/CD: Add a GitHub Action Bot to tag PRs with merge conflicts 

### ISSUE THREAD

**Issue by HarshCasper** [TesseractCoding/NeoAlgo-Docs#160]
## Description

Add a GitHub Action Bot to tag PRs with merge conflicts. The Bot should do the following: 

- Tag a PR with `merge-conflicts` label if it runs into a merge conflict. Remove it up once it has been resolved.
- Comment instructions to resolve merge conflicts by quoting GitHub Docs. 
- Remind the PR author every 24 hours if the merge conflicts is not fixed.

**Comment by rubyruins** [comment]
Hi! I would like to work on this. However, I've never created a Github bot before. I think I could manage the auto labelling and commenting part, but am a bit confused about how we could implement the third part?

**Comment by HarshCasper** [comment]
> Hi! I would like to work on this. However, I've never created a Github bot before. I think I could manage the auto labelling and commenting part, but am a bit confused about how we could implement the third part?

No worries! Let us first go with the needful first and then you can extend another PR to do the third after a discussion.

**Comment by rubyruins** [comment]
Thanks! I'll get started soon.
