### ISSUE TITLE
Doc of unbounded knapsack

### ISSUE THREAD

**Issue by SAY-droid427** [TesseractCoding/NeoAlgo-Docs#171]
## 💥 Proposal

I want to create the doc for unbounded knapsack. I will use my own code which I have written in NeoAlgo

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by SAY-droid427** [comment]
@HarshCasper Please assign this to me

**Comment by SAY-droid427** [comment]
@HarshCasper I am facing a problem. My previous commits are also getting pushed when I made a pull request for this issue like in this PR which I closed https://github.com/TesseractCoding/NeoAlgo-Docs/pull/192 . Could you please guide me a bit in this?

**Comment by HarshCasper** [comment]
> @HarshCasper I am facing a problem. My previous commits are also getting pushed when I made a pull request for this issue like in this PR which I closed #192 . Could you please guide me a bit in this?

Delete a branch when your PR gets merged/closed. Pull from the upstream and create a new branch and push your commits on that. Let me know on Discord if you face further problems.
