### ISSUE TITLE
Article for Preorder traversal of binary tree

### ISSUE THREAD

**Issue by shivammahajancse** [TesseractCoding/NeoAlgo-Docs#178]
## 🚀 Feature

I would like to add an article for Preorder traversal of binary tree. The basic layout for the article will be:

What is Preorder traversal?
Explanation for Preorder traversal
Algorithmic Steps
Code (Use C++/Java and Python; At least two languages should be present and pick up code from NeoAlgo with apt credits to author)
Sample I/O
Time & Space Complexity
This article should be between 300-400 words in length. You should use traditional Markdown to prepare the content and the use of external images is prohibited. You can however create your own images. Run a proper Grammarly Lint check before submitting the PR.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Yes)

**Comment by shivammahajancse** [comment]
Please assign me sir @ankitaggarwal23 @HarshCasper @iamrajiv @gat786 @atarax665

**Comment by atarax665** [comment]
@shivammahajancse You can start working on this. 👍
