### ISSUE TITLE
Blog: How do Websites search for Usernames so efficiently? 

### ISSUE THREAD

**Issue by HarshCasper** [TesseractCoding/NeoAlgo-Docs#188]
## Background

Did you ever wonder, how many popular websites like GitHub, or Reddit, Inc. are able to implement features that allow you to see if a particular Username is taken or not?

If we take into account, the Linear Search Algorithm, finding a Username would be too expensive. Binary Search is more efficient, as the maximum number of comparisons we make is equal to the binary logarithm of the total number of Users.

Another efficient methodology can be using Hashing, which works in constant time. However, with each entry, the Database needs to be rehashed. So, what is a better option?

The one algorithm that is really designed to scale is Bloom Filter. It is a probabilistic data structure that is used to determine whether an element is present in a given list.

Bloom Filters are increasingly used to check if a username is taken or if a certain action you have performed has already been performed. Some of its best applications include Tinder, Aadhar and even YouTube.

## Description 

Write a blog of 1000-1500 words detailing all the methods that can be utilized for this purpose. Remember you can write or pic your own code from NeoAlgo and make PRs to the upstream for the upstream. 

The Blog should: 

- Be conversational in nature rather than instructional (like articles) 
- Be check by Grammarly and a Google Doc shared in the PR for review over them
- Uses active diagrams and infographics to explain the idea 
- Unnecessary jargons are not needed and use as plain English as possible 
- Add your metadata properly to the same

**Comment by VinayakChopra** [comment]
@HarshCasper I would like to work on this!
