### ISSUE TITLE
Add PWA support for NeoAlgo Docs

### ISSUE THREAD

**Issue by HarshCasper** [TesseractCoding/NeoAlgo-Docs#199]
## Description

Add PWA support for NeoAlgo Docs. Here is the [plugin-pwa](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-pwa) from the official documentation.

**Comment by TidbitsJS** [comment]
I will like to work on this @HarshCasper 🤓

**Comment by TidbitsJS** [comment]
@HarshCasper, I will be needing different icons with a particular size ratio for different browsers.
Do you have such a set of icons?

**Comment by HarshCasper** [comment]
Here you go :)

https://imgur.com/a/wZkBG9z

Maybe you might need to resize them as per the needs.
