### ISSUE TITLE
Develop a Style handbook

### ISSUE THREAD

**Issue by HarshCasper** [TesseractCoding/NeoAlgo-Docs#2]
## Description

As a first-time contributor, many people aren't aware of the Markdown Style that needs to be followed while working on a Documentation Site. Create a Style Handbook titled `STYLE-GUIDELINES.md` which would be then added to the site. 

The Style Handbook would extract information from [here](https://github.com/TesseractCoding/NeoAlgo-Docs/blob/main/docs/markdown-features.mdx) and would make it specific to our Docs.

**Comment by anjali7786** [comment]
@HarshCasper please assign this issue to me as a part of GSSOC'21
