### ISSUE TITLE
Add Vercel Logo + Vercel Banner on README [Vercel Sponsorship]

### ISSUE THREAD

**Issue by HarshCasper** [TesseractCoding/NeoAlgo-Docs#210]
## Background

We are applying for @Vercel sponsorship for Open-Source Projects. As part of this sponsorship, they have a few criteria that we should satisfy: 

- A Vercel banner in the footer of each site page.
- A Vercel banner in the source repository's README.md file.
- All links back to Vercel should use a UTM tag with the format: ?utm_source=[team-name]&utm_campaign=oss (Our team name is `NeoAlgo-Docs`)

See the full list of criteria:
https://vercel.com/knowledge/can-vercel-sponsor-my-open-source-project

Here is the banner image: https://github.com/nextauthjs/next-auth/blob/canary/www/static/img/powered-by-vercel.svg

**Comment by rubyruins** [comment]
Hi, could I work on this?
