### ISSUE TITLE
Content: Jarvis Algorithm

### ISSUE THREAD

**Issue by HarshCasper** [TesseractCoding/NeoAlgo-Docs#23]
## Description 

Add the article for `Jarvis Algorithm`. The basic layout for the article should be: 

- What is Jarvis Algorithm?
- Explanation for Jarvis Algorithm
- Algorithmic Steps 
- Code (Use C++/Java and Python; At least two languages should be present and pick up code from NeoAlgo with apt credits to author)
- Sample I/O 
- Time & Space Complexity 

This article should be between 500-700 words in length. You should use traditional Markdown to prepare the content and the use of external images is prohibited. You can however create your own images. Run a proper Grammarly Lint check before submitting the PR.

**Comment by balajigupta14** [comment]
I have made

**Comment by Inventor77** [comment]
> I have made

@balajigupta14 what you made

**Comment by balajigupta14** [comment]
I have made advance Jarvis already

**Comment by balajigupta14** [comment]
I can give you code if you want

**Comment by Inventor77** [comment]
> I can give you code if you want

@balajigupta14 Yess please share it.

**Comment by balajigupta14** [comment]
Ok

**Comment by balajigupta14** [comment]
import pyttsx3

import speech_recognition as sr
import datetime
import wikipedia
import time
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.keys import Keys
from selenium import webdriver
import pyautogui
# Use female voice
import pyperclip
hiddenimports = [
   'pyttsx3.drivers',
   'pyttsx3.drivers.dummy',
   'pyttsx3.drivers.espeak',
   'pyttsx3.drivers.nsss',
   'pyttsx3.drivers.sapi5', ]

engine = pyttsx3.init('sapi5')

voices = engine.getProperty('voice')
engine.setProperty('voice', voices)
engine.setProperty('rate', 150)
engine.setProperty('volume', 10)

def speak(audio):
 engine.say(audio)
 engine.runAndWait()

def wishMe():
   hour = int(datetime.datetime.now().hour)
   if hour>=0 and hour<12:
       speak("Good Morning!")
   elif hour>=12 and hour<18:
       speak("Good Afternoon!")
   else:
       speak("Good Evening!")
   speak("I am friday, is there anything to help you sir?")

def takecommand():
    r = sr.Recognizer()
    with sr.Microphone() as source:
        print("Listening....")
        r.pause_threshold = 1
        audio = r.listen(source)
    try:
        print("Recognizing....")
        query = r.recognize_google(audio, language='en-in')
        print(f"user said: {query}\n")
    except Exception as e:
        print(e)
        return "None"
    return query


def typenh():
   r = sr.Recognizer()
   with sr.Microphone() as source:
       print("Listening....")
       r.pause_threshold = 1
       audio = r.listen(source)
   try:
    print("Recognizing....")
    typethingh = r.recognize_google(audio, language='hi')
    print(f"user said: {typethingh}\n")
   except Exception as e:
     print(e)
     speak("sorry I could not understand, say that again please...")
     return "None"
   return typethingh

i = 0

#Edited From Here
n = 0
k = 0

print("Say Hey Jarvis To Begin Initiation Sequence") #Sounds SICK Right!
while (i<1):
    r = sr.Recognizer()
    with sr.Microphone() as source:
        audio = r.adjust_for_ambient_noise(source)
        n=(n+1)
        audio = r.listen(source)
        # interprete audio (Google Speech Recognition)
    try:
        s = (r.recognize_google(audio))
        message = (s.lower())

        if message == "hey jarvis":
            wishMe()
            k = 0
            while k == 0:
                query = takecommand().lower()
                query.replace("could you", "")
                query.replace("please", "")

                if 'sleep' in query:
                    speak("Entering Sleep Mode. Say Hey Jarvis To Wake Me Up!")
                    k = 1
                    print("Say Hey Jarvis To Begin Initiation Sequence")
                    #Editing Ends Here
                if 'wikipedia' in query:
                       speak('searching Wikipedia...')
                       query = query.replace("wikipedia", "")
                       results = wikipedia.summary(query, sentences=2)
                       speak("according to wikipedia")
                       speak(results)
                if 'manav sampada' in query:
                       speak('loging in to manav sampada')
                       browser = webdriver.Chrome('D:\\chromedriver.exe')
                       browser.get('http://ehrms.upsdc.gov.in/')
                       elem = browser.find_element_by_partial_link_text('eHRMS Login')
                       elem.get_attribute('href')
                       time.sleep(1)
                       elem.click()
                       time.sleep(1)
                       loginr = browser.find_element_by_xpath('//*[@id="txtusername"]')
                       loginr.send_keys('your id ')
                       time.sleep(1)
                       select = Select(browser.find_element_by_id('ddldept'))
                       select.select_by_visible_text('Basic Education')
                       time.sleep(1)
                       password = browser.find_element_by_xpath('//*[@id="txtpwd"]')
                       password.send_keys('your password')
                       speak('sir I have filled all userID password etc. but ')
                       speak('sir you have to fill the human verification captha by yourself as I am just a bot ')
                       speak('I hope I was able to assist you')
                if 'software' in query:
                       speak('opening sir')
                       query = query.replace("software", "")
                       pyautogui.click(27, 880)
                       pyautogui.typewrite(query)
                       time.sleep(1)
                       pyautogui.click(79,441)
                if 'send' and 'gmail' in query:
                       speak('opening gmail')
                       browser = webdriver.Chrome('D:\\chromedriver.exe')
                       browser.get('https://accounts.google.com/b/0/AddMailService')
                       time.sleep(1)
                       login = browser.find_element_by_xpath('//*[@id="identifierId"]')
                       login.send_keys('your gmail id @gmail.com')
                       login.send_keys(Keys.ENTER)
                       time.sleep(1)
                       loginpwd = browser.find_element_by_xpath('//*[@id="password"]/div[1]/div/div[1]/input')
                       loginpwd.send_keys('your awesom password here')
                       loginpwd.send_keys(Keys.ENTER)
                       time.sleep(10)
                       try:
                           speak('just a sec')
                           compose = browser.find_element_by_class_name('z0')
                           time.sleep(2)
                           compose.click()
                           time.sleep(1)
                           speak('whom do you want to send the gmail')
                           sendto = takecommand().lower()
                           sendto = ''.join(sendto.split())
                           tom = browser.find_element_by_name('to')
                           tom.send_keys(sendto)
                           speak('what is the subject?')
                           subject = browser.find_element_by_name('subjectbox')
                           time.sleep(0.5)
                           
                           whatissu = takecommand()
                           subject.send_keys(whatissu)
                           body = browser.find_element_by_name('Message Body')
                           speak('what is the main body?')
                           mainbody = takecommand()
                           body.send_keys(mainbody)

                       except Exception as identifier:
                           compose = browser.find_element_by_xpath('//*[@id=":jm"]/div/div')
                           time.sleep(1)
                           compose.click()
                           time.sleep(1)
                           speak('whom do you want to send the gmail')
                           sendto = takecommand().lower()
                           sendto = ''.join(sendto.split())
                           tom = browser.find_element_by_name('to')
                           tom.send_keys(sendto)                                                   
                           subject = browser.find_element_by_name('subjectbox')
                           time.sleep(0.5)
                           speak('what is the subject?')
                           whatissu = takecommand()
                           subject.send_keys(whatissu)
                           body = browser.find_element_by_name('Message Body')
                           speak('what is the main body?')
                           mainbody = takecommand()
                           body.send_keys(mainbody)            
                   
                if 'hindi' in query:
                   speak('what to type?')
                   typethingh = typenh()
                   content = typethingh
                   pyperclip.copy(content)
                   time.sleep(0.5)
                   pyautogui.hotkey('ctrl', 'v')

                if 'do you have a boyfriend' in query:
                    speak('I am happy to be single')

                if 'siri' in query:
                    speak('siri is smart but I dont like him')

                if 'how are you' in query:
                    speak('I am good ')

                if 'i hate you' in query:
                    speak('than go to siri or google. why are you even talking to me')

                if 'who is your creator' in query:
                    speak("my creater is John Cena(The OG Himself)")

                if 'who made you' in query:
                    speak('John Cena Made e. He Is An OG!')

                if 'who created you' in query:
                    speak('Booooob The BUILDER!!!')

                if 'whatsapp' in query:
                    browser = webdriver.Chrome('D:\\chromedriver.exe')
                    speak('opening whatsapp web')
                    browser.get('https://web.whatsapp.com/')
                    speak('please scan the qr code. I am waiting for 10 seconds')
                    time.sleep(10)
                    try:
                        find = browser.find_element_by_xpath('//*[@id="side"]/div[1]/div/label/div/div[2]')
                        find.click()
                        speak('tell the first word of the contact to whom you want to send the messege')
                        sendmsg = takecommand()
                        find.send_keys(sendmsg)
                        time.sleep(1.5)
                        find.send_keys(Keys.ENTER)
                        try:
                            typenum = browser.find_element_by_xpath('//*[@id="main"]/footer/div[1]/div[2]/div/div[2]')
                            typenum.click()
                            speak('what do you want to send sir?')
                            whattosend = takecommand()
                            typenum.send_keys(whattosend)
                            typenum.send_keys(Keys.ENTER)
                        except Exception as identifier:
                            speak('there is no contact as'+sendmsg)
                    except Exception as identifier:
                        speak('you did not make it in 10 seconds')


                if 'quit' in query:
                   exit()

    except Exception as e:
        pass

**Comment by balajigupta14** [comment]
import pyttsx3  #it import's the voice
import speech_recognition as sr #it do text to speech function
import datetime #this moudle wishes me acording to time eg:goodmorning,goodevening,tells the time
import wikipedia #this search my speech in wikipedia
import webbrowser
import pywhatkit
import pyjokes

def speak (audio):
    engine.say(audio)
    engine.runAndWait()
engine = pyttsx3.init('sapi5') #this is voice that i have use from pyttsx3
voices = engine.getProperty('voices')
# engine.setProperty('voice',voices[0].id)   #This is optional

def wishme():
    hour = int(datetime.datetime.now().hour)
    if hour>= 0 and hour<12:
        speak('Good morning sir!')

    elif hour>= 12 and hour<18:
        speak('good Afternoon sir!')

    else:
        speak('good Evening sir!')

    speak('I am Jarvis. Please tell me how may i help you')

def Takecommand():
    r = sr.Recognizer()
    with sr.Microphone() as source:
        print("listning...")
        r.pause_threshold = 1
        audio = r.listen(source)

        try:
            print('Recognising...')
            quary = r.recognize_google(audio, language='en-US')
            if "jarvis" in quary:
                quary = quary.replace("jarvis", "")
            print(f"user said:{quary}")

        except Exception as e:
            print('Say that again please...')
            return "None"
        return quary

if __name__ == "__main__":
    wishme()
    while True:
        quary = Takecommand().lower()

    #logic for executing task based on quary.
        if 'wikipedia' in quary:
            speak('searching Wikipedia....')
            quary = quary.replace('Wikipedia',"")
            results = wikipedia.summary(quary, sentences=2)
            speak('According to Wikipedia')
            print(results)
            speak(results)


        elif 'open youtube' in quary:
            webbrowser.open("youtube.com")

        elif 'tell me about great mathematician' in quary:
            speak('Srinivasa Ramanujan, (born December 22, 1887, Erode, India—died April 26, 1920, Kumbakonam), Indian 		mathematician whose contributions to the theory of numbers include pioneering discoveries of the properties 		of the partition function.Dec 22, 2020 Died: April 26, 1920, KumbakonamBorn: December 22, 1887, Erod Works 	written: 		Ramanujan’s Notebooks: Part III Profession: Mathematician. He is the elected fallow of 		royal society')

        elif 'what should i call you' in quary:
            speak('sir you should call me jarvis. Because thats my name.')

        elif 'ok' in quary:
            speak('yes sir')

        elif 'why you are slow' in quary:
            speak('sorry sir i will improve it')

        elif 'open google' in quary:
            webbrowser.open("google.com")

        elif 'open whatsapp' in quary:
            webbrowser.open("https://web.whatsapp.com")

        elif 'open facebook' in quary:
            webbrowser.open("facebook.com")

        elif 'keep quiet' in quary:
            speak('ok sir')

        elif 'who are you' in quary:
            speak("i am Jarvis i want love")

        elif 'what is your name' in quary:
            speak("My name is jarvis")

        elif 'what should i study' in quary:
            speak('you should study maths because your maths is little weak')

        elif 'good' in quary:
            speak('thank you sir')

        elif 'how many days are there in a week' in quary:
            speak('their are seven days in a week')

        elif 'how many months are there in a year' in quary:
            speak('there are 12 months in a year')

        elif 'introduce yourself' in quary:
            speak("""
            I am jarvis assistant of my sir balaji gupta. 
            I am the future and an AI assistant, I can do everything. I am every thing. 
            I am very inteligent.
            I never lie.
            """)

        elif 'thank you' in quary:
            speak('Welcome sir')

        elif 'open classroom' in quary:
            webbrowser.open('classroom.google.com')

        elif 'i want to talk with you' in quary:
            speak('of course')

        elif 'what do you eat' in quary:
            speak('i eat battery ')

        elif "you are a good assistant" in quary:
            speak('thank you sir ')

        elif 'should i bath' in quary:
            speak('yes, you should bath every day')

        elif 'pubg' in quary:
            speak('Hey!, sir I think you donot nedd to play these games ')

        elif 'who made you' in quary:
            speak("Balaji gupta has made me. He is a genious")

        elif 'nice work' in quary:
            speak("thank you sir")

        elif 'help me' in quary:
            speak("tell me how can i help you")

        elif 'what can you do' in quary:
            speak("i can help you in many ways")

        elif 'like' in quary:
            speak("open web applications,search in wikipedia else i can do many work. If you develop me")

        elif 'the time' in quary:
            strTime = datetime.datetime.now().strftime("%H:%M:%p:%a")
            print(strTime)
            speak(f"Sir, the time is {strTime}")

        elif 'go to sleep' in quary:
            speak("quiting")
            break

        if 'play' in quary:
            speak("playing")
            song = quary.replace('play', '')
            print("playing" + song)
            pywhatkit.playonyt(song)

        elif "tell me a joke" in quary:
            speak(pyjokes.get_joke())

**Comment by balajigupta14** [comment]
These are two I have made hope it helps you
