### ISSUE TITLE
Content: Vigenere Cipher

### ISSUE THREAD

**Issue by Ayushjain2205** [TesseractCoding/NeoAlgo-Docs#257]
## 📚 Documentation

Add content for Vigenere Cipher

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by Ayushjain2205** [comment]
@iamrajiv Can you please assign this issue to me

**Comment by Ayushjain2205** [comment]
Just found out it already exists , sorry for the trouble, closing the issue

**Comment by nidh-ish** [comment]
@Ayushjain2205 I don't see it anywhere. Has somebody else created the same issue? Because it is not on the website already.
