### ISSUE TITLE
Content: Interpolation Search

### ISSUE THREAD

**Issue by HarshCasper** [TesseractCoding/NeoAlgo-Docs#29]
## Description 

Add the article for `Interpolation Search`. The basic layout for the article should be: 

- What is Interpolation Search? 
- Explanation for Interpolation Search
- Algorithmic Steps 
- Code (Use C++/Java and Python; At least two languages should be present and pick up code from NeoAlgo with apt credits to author)
- Sample I/O 
- Time & Space Complexity 

This article should be between 500-700 words in length. You should use traditional Markdown to prepare the content and the use of external images is prohibited. You can however create your own images. Run a proper Grammarly Lint check before submitting the PR.

**Comment by geekymeeky** [comment]
I would like to work on this issue as a participant of GSSoC'21. Please assign this to me.

**Comment by HarshCasper** [comment]
Hi @geekymeeky   

Few instructions: 

- Install the Project locally. You need to use NodeJS and Yarn (Instructions are on README.md)
- Find the directory in `src` where this should ideally go. Let's say it goes in `searching-algorithms`, so create a file in there named `interpolation-search.md`
- Once you do that, go over to [sidebar.js](https://github.com/TesseractCoding/NeoAlgo-Docs/blob/main/sidebars.js) in your forked repo, and go over to [this line](https://github.com/TesseractCoding/NeoAlgo-Docs/blob/781088e0adbcebf313213e937ebe5ed21564bbd2/sidebars.js#L17) and add `searching-algorithms/interpolation-search.md`
- Always check the application build and see if your article is being correctly rendered on the local server

Let me know if you need more help with this. We would be glad to have you contribute!
