### ISSUE TITLE
Develop a Doc Guideline

### ISSUE THREAD

**Issue by HarshCasper** [TesseractCoding/NeoAlgo-Docs#3]
## Description 

We need to have a Doc Guideline so that the new contributors know on how they can format their articles for publishing over the website. Right now we have two types of content: 
- Docs
- Blogs 

Blogs are reserved for the core maintainers unless stated otherwise. The Docs would consist of articles over various Data Structures and Algorithms that are available on the upstream (NeoAlgo) repository. Your Doc Guideline should contain information and basic sections on how someone can write an article for the website. 

You can get inspired from these: 

- [GeeksForGeeks reference](https://write.geeksforgeeks.org/how-to-write/)
- [Rotten Scripts reference](https://github.com/HarshCasper/Rotten-Scripts/blob/master/TEMPLATE_README.md)

**Comment by SAY-droid427** [comment]
I would like to work on this issue. Please assign it to me @HarshCasper
