### ISSUE TITLE
Contributing Guidelines

### ISSUE THREAD

**Issue by geekymeeky** [TesseractCoding/NeoAlgo-Docs#35]
### Contributing Guidelines

This documentation will contains a set of guidelines to help people during the contributing process.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by geekymeeky** [comment]
As a participant of GSSoC'21, I would like to work on this issue.

**Comment by HarshCasper** [comment]
Hi @geekymeeky 

Thanks for taking it up! Please feel free to take some material from [here](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md). 

Overall focus on creating a Contributor's Guide that would encompass the following: 

- How to create an Issue? 
- How to create a Pull Request? 
- How to add a new article? 
- How to add a new blog? 
- Getting PRs reviewed

**Comment by nagasrihith608** [comment]
@HarshCasper yea sure I can work on this😀

**Comment by HarshCasper** [comment]
> @HarshCasper yea sure I can work on this

A PR is open for it now. You already have a lot of Issues under your belt.

**Comment by geekymeeky** [comment]
Closed via #87
