### ISSUE TITLE
Article on Factorial of large number

### ISSUE THREAD

**Issue by Amit366** [TesseractCoding/NeoAlgo-Docs#367]
## 📚 Documentation

Add article for Factorial of large number

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by Amit366** [comment]
@HarshCasper please assign it to me

**Comment by satcasm** [comment]
@Amit366 I am already working on this issue and PR is almost ready. Kindly open another issue .

**Comment by Amit366** [comment]
@satcasm have u opened the issue??

**Comment by satcasm** [comment]
Yes. #155
