### ISSUE TITLE
comb sort

### ISSUE THREAD

**Issue by nagasrihith608** [TesseractCoding/NeoAlgo-Docs#376]
## 📚 Documentation

(A clear and concise description of what the issue is.)
comb sort
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
yes

**Comment by ankitaggarwal23** [comment]
This is strictly against the guidelines you have not been assigned to any of the issues and you have spammed it by opening 10+ issue in the repo which is strictly unfair with other participants. I'm closing all your issues and PR. As we are at the end of the program. Thank you for your contribution😊
