### ISSUE TITLE
Multiple Binary Search Tree

### ISSUE THREAD

**Issue by Saatvik21** [TesseractCoding/NeoAlgo-Docs#399]
## 🐛 Bug Report

There are currently multiple articles of BST. I would like to remove the duplicate ones from the sidebar.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

`Yes`
![Screenshot_1](https://user-images.githubusercontent.com/61618767/115230307-c9709480-a131-11eb-9574-fbaaefd8ddbb.png)

**Comment by Saatvik21** [comment]
@HarshCasper this issue is important, so please look into this.

**Comment by vybhav72954** [comment]
@ankitaggarwal23 @anushkrishnav @bhav09
