### ISSUE TITLE
Add Twitter Card and Tesseract Coding logo to the Open Graph Image metadata of https://neoalgo.tesseractcoding.com 

### ISSUE THREAD

**Issue by iamrajiv** [TesseractCoding/NeoAlgo-Docs#43]
## 🚀 Feature

When we share https://neoalgo.tesseractcoding.com over social media like Twitter, it is good that the card they generate for the link has useful information.

![Screenshot 2021-04-08 at 4 21 59 AM](https://user-images.githubusercontent.com/42106787/113944324-f9f72b00-9821-11eb-84dc-36fd2c23092b.jpg)

Currently, Twitter does not render and get any image to use for https://neoalgo.tesseractcoding.com.

### Possible Implementation:

Add an [og:image](https://ogp.me) metadata to the website and use the Tesseract Coding logo. Use png instead of SVG here.

### Context:

Use https://cards-dev.twitter.com/validator to validate results.

**Comment by rubyruins** [comment]
Hi, could I take this up?

**Comment by HarshCasper** [comment]
@rubyruins Good Work on your PR! 

Give us sometime to review. You can work on this and let us know if you need brand assets of Tesseract Coding.

**Comment by rubyruins** [comment]
Thank you @HarshCasper :) take your time! Where can I find the brand assets, by the way?

**Comment by HarshCasper** [comment]
Here you go :) 

https://imgur.com/a/wZkBG9z

**Comment by rubyruins** [comment]
Thanks!

**Comment by rubyruins** [comment]
Hi @HarshCasper, is it fine to use any of the images? Also, (I am currently using the square blue outline logo) should I download and add the image I am using to the static folder?

**Comment by HarshCasper** [comment]
> Hi @HarshCasper, is it fine to use any of the images? Also, (I am currently using the square blue outline logo) should I download and add the image I am using to the static folder? Plus, in `twitter:card`, is there a specific summary you would like to put?

Use any image. You can put image in the `static` directory. For `twitter:card` use `Bringing all Data Structures and Algorithms under one Roof ⚡`

**Comment by rubyruins** [comment]
Alright, thanks! Will send a PR for it soon :)
