### ISSUE TITLE
Documentation for factorial of a number

### ISSUE THREAD

**Issue by nidh-ish** [TesseractCoding/NeoAlgo-Docs#57]
## 📚 Documentation

Documentation for factorial of a number.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes
Please assign this to me under GSSOC'21.

**Comment by umamanasir** [comment]
Hi. I can write the documentation for calculating the factorial of a number. 
It will contain code snippets in C++, Python, Java (Will use code from NeoAlgo, crediting authors as well). 
The pseudocode will also be written as well as a concise, clear explanation. 
Kindly assign it to me under GSSoC '21 tag. 
Thank you.

**Comment by nidh-ish** [comment]
> Hi. I can write the documentation for calculating the factorial of a number.
> It will contain code snippets in C++, Python, Java (Will use code from NeoAlgo, crediting authors as well).
> The pseudocode will also be written as well as a concise, clear explanation.
> Kindly assign it to me under GSSoC '21 tag.
> Thank you.

Hey. I have asked about this issue. You can open other issues for documentation.

**Comment by umamanasir** [comment]
> > Hi. I can write the documentation for calculating the factorial of a number.
> > It will contain code snippets in C++, Python, Java (Will use code from NeoAlgo, crediting authors as well).
> > The pseudocode will also be written as well as a concise, clear explanation.
> > Kindly assign it to me under GSSoC '21 tag.
> > Thank you.
> 
> Hey. I have asked about this issue. You can open other issues for documentation.

oh okay! Apologies. I thought someone from the main team created an issue.
