### ISSUE TITLE
Automorphic Number

### ISSUE THREAD

**Issue by nagasrihith608** [TesseractCoding/NeoAlgo-Docs#58]
## 📚 Documentation

(A clear and concise description of what the issue is.)
Automorphic Number
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
yes

please assign this issue to me

**Comment by Inventor77** [comment]
@HarshCasper @nagasrihith608   I would love to work in this Issue Please Assign this to me

**Comment by HarshCasper** [comment]
Hi @Inventor77 

You already have a lot of issues under your belt.

**Comment by Inventor77** [comment]
> Hi @Inventor77 
> 
> You already have a lot of issues under your belt.

@HarshCasper Sir I will work on Them All please Assign them to me

**Comment by nagasrihith608** [comment]
hello @Inventor77, I had opened this issue to work on. You can open your own issue :) .

**Comment by Inventor77** [comment]
> hello @Inventor77, I had opened this issue to work on. You can open your own issue :) .

Soory I thought It is opened by mentors

**Comment by nagasrihith608** [comment]
@Inventor77 Np :)
