### ISSUE TITLE
The text on Get Started Button on Homepage becomes illegible on hovering

### ISSUE THREAD

**Issue by N-Shar-ma** [TesseractCoding/NeoAlgo-Docs#62]
## 🐛 Bug Report

On hovering, the background color of the button becomes nearly identical to the text color, hampering readability

### Have you read the [Contributing Guidelines on Pull Requests]
yes

**Comment by HarshCasper** [comment]
Hi @N-Shar-ma 

Would you like to work on it?

**Comment by N-Shar-ma** [comment]
@HarshCasper Sure, I would love to!
