### ISSUE TITLE
Article for BFS

### ISSUE THREAD

**Issue by SalmaZakaria** [TesseractCoding/NeoAlgo-Docs#63]
## 📚 Documentation

(A clear and concise description of what the issue is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

How BFS works and Implementation of it in c#

**Comment by nagasrihith608** [comment]
hey, @SalmaZakaria will you be working on this issue? If not please let me know I will be doing it.

**Comment by SalmaZakaria** [comment]
@nagasrihith608 I am working on it
