### ISSUE TITLE
Content: Linked Lists

### ISSUE THREAD

**Issue by vgb-codes** [TesseractCoding/NeoAlgo-Docs#67]
Add the article for `Linked Lists`. The basic layout for the article should be:

- What are Linked Lists?
- Explanation for Linked List
- Algorithmic Steps
- Code (Use C++/Java and Python; At least two languages should be present and pick up code from NeoAlgo with apt credits to author)
- Sample I/O
- Time & Space Complexity

This article should be between 500-700 words in length. You should use traditional Markdown to prepare the content and the use of external images is prohibited. You can however create your own images. Run a proper Grammarly Lint check before submitting the PR.

**Comment by SAY-droid427** [comment]
@vgb-codes Please assign this issue to me. I would like to work on it.
