### ISSUE TITLE
Content: Heap

### ISSUE THREAD

**Issue by vgb-codes** [TesseractCoding/NeoAlgo-Docs#69]
Add the article for `Heap`. The basic layout for the article should be:

- What is Heap?
- Explanation for Heap
- Algorithmic Steps
- Code (Use C++/Java and Python; At least two languages should be present and pick up code from NeoAlgo with apt credits to author)
- Sample I/O
- Time & Space Complexity

This article should be between 500-700 words in length. You should use traditional Markdown to prepare the content and the use of external images is prohibited. You can however create your own images. Run a proper Grammarly Lint check before submitting the PR.

**Comment by Kavitam23** [comment]
I would like to contribute to this. Can you please assign it to me?

**Comment by deeptea22** [comment]
I would like to work on this issue, if it is still available.
@bhav09 @gat786 @iamrajiv Kindly assign me to this under gssoc21.
Thank you :)
