### ISSUE TITLE
Content: Singly Linked list

### ISSUE THREAD

**Issue by ankitaggarwal23** [TesseractCoding/NeoAlgo-Docs#72]
## Description 

Add the article for `Singly Linked list`. The basic layout for the article should be: 

- What is Singly Linked list?
- Explanation for Singly Linked list
- Algorithmic Steps 
- Code (Use C++/Java and Python; At least two languages should be present and pick up code from NeoAlgo with apt credits to author)
- Sample I/O 
- Time & Space Complexity 

This article should be between 500-700 words in length. You should use traditional Markdown to prepare the content and the use of external images is prohibited. You can however create your own images. Run a proper Grammarly Lint check before submitting the PR.

**Comment by madihamallick** [comment]
@HarshCasper I would like to work on this issue. Kindly assign this to me.
