### ISSUE TITLE
Content: Doubly Linked List

### ISSUE THREAD

**Issue by ankitaggarwal23** [TesseractCoding/NeoAlgo-Docs#73]
## Description 

Add the article for `Doubly Linked List`. The basic layout for the article should be: 

- What is Doubly Linked List?
- Explanation for Doubly Linked List
- Algorithmic Steps 
- Code (Use C++/Java and Python; At least two languages should be present and pick up code from NeoAlgo with apt credits to author)
- Sample I/O 
- Time & Space Complexity 

This article should be between 500-700 words in length. You should use traditional Markdown to prepare the content and the use of external images is prohibited. You can however create your own images. Run a proper Grammarly Lint check before submitting the PR.

**Comment by Saatvik21** [comment]
I would like to work on this issue.

**Comment by Kavitam23** [comment]
I would like to contribute to this . Kindly assign it to me.

**Comment by deeptea22** [comment]
I would like to work on this issue, if it is still available.
@bhav09 @gat786 @iamrajiv Kindly assign me to this under gssoc21.
Thank you :)

**Comment by gat786** [comment]
@Kavitam23 has not yet raised a pr so you should be good to go. Unless @Kavitam23 you are still working on it?

**Comment by Kavitam23** [comment]
> @Kavitam23 has not yet raised a pr so you should be good to go. Unless @Kavitam23 you are still working on it?

I'm still working on it. Just need few days more

**Comment by deeptea22** [comment]
I 

> > @Kavitam23 has not yet raised a pr so you should be good to go. Unless @Kavitam23 you are still working on it?
> 
> I'm still working on it. Just need few days more

I am already done with the article. In case you are not taking this up please let me know.
@gat786
