### ISSUE TITLE
Content: Circular Linked List

### ISSUE THREAD

**Issue by ankitaggarwal23** [TesseractCoding/NeoAlgo-Docs#74]
## Description 

Add the article for `Circular Linked List`. The basic layout for the article should be: 

- What is Circular Linked List?
- Explanation for Circular Linked List
- Algorithmic Steps 
- Code (Use C++/Java and Python; At least two languages should be present and pick up code from NeoAlgo with apt credits to author)
- Sample I/O 
- Time & Space Complexity 

This article should be between 500-700 words in length. You should use traditional Markdown to prepare the content and the use of external images is prohibited. You can however create your own images. Run a proper Grammarly Lint check before submitting the PR.

**Comment by Inventor77** [comment]
@ankitaggarwal23  I would love to work in this Issue Please Assign this to me

**Comment by HarshCasper** [comment]
Hi @Inventor77 

You already have a lot of issues under your belt.

**Comment by Inventor77** [comment]
> Hi @Inventor77 
> 
> You already have a lot of issues under your belt.

@HarshCasper Sir I will work on Them All please Assign them to me

**Comment by madihamallick** [comment]
@HarshCasper I would like to work on this issue. Please assign this to me.
