### ISSUE TITLE
Content: Reverse a Number

### ISSUE THREAD

**Issue by tk315** [TesseractCoding/NeoAlgo-Docs#82]
## 🚀 Feature
An article on reversing a number

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

**Comment by Kavitam23** [comment]
I want to contribute on this . Kindly assign it to me.

**Comment by tk315** [comment]
@HarshCasper Please assign me the issue
