### ISSUE TITLE
Content: Sum of Divisors

### ISSUE THREAD

**Issue by tk315** [TesseractCoding/NeoAlgo-Docs#84]
## 🚀 Feature
An article on sum of divisors

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

**Comment by HarshCasper** [comment]
Hi @tk315 

Why are you closing the Issues?

**Comment by tk315** [comment]
Sir I thaought there can be two open issues

**Comment by HarshCasper** [comment]
Yes @tk315 

Please get the existing PR work done. I will assign them then to you

**Comment by tk315** [comment]
@HarshCasper Please assign me the issue
