### ISSUE TITLE
Changing the title and subtitle on main page when dark mode is on.

### ISSUE THREAD

**Issue by gat786** [TesseractCoding/NeoAlgo-Docs#90]
## 💥 Proposal

To change the title and subtitle color to white when the dark mode is on. For reference 

![image](https://user-images.githubusercontent.com/22629774/114137341-abcd4f00-9929-11eb-9c98-fa7b2c33febd.png)

This is something which I did with inspect element and it looks better than what we have in place currently.

![image](https://user-images.githubusercontent.com/22629774/114137174-6b6dd100-9929-11eb-85b5-730a43e1e518.png)

Also, the text color of button on hover looks to merge with bg color so we should think about changing it if it makes sense

![image](https://user-images.githubusercontent.com/22629774/114137473-e800af80-9929-11eb-8712-8a7962651d31.png)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by HarshCasper** [comment]
Fixed now!
