### ISSUE TITLE
Simplifying the code of C++ in Already published article

### ISSUE THREAD

**Issue by siddharth25pandey** [TesseractCoding/NeoAlgo-Docs#92]
## 🐛 Bug Report

(A clear and concise description of what the bug is.)
The article for **Factorial of a number** has a lengthy & complex code  written in **C++** for finding out the factorial for the given number.
Here is the [link](https://neoalgo.tesseractcoding.com/docs/mathematics/factorial-of-number) for the article
It would be better if anyone can simplify the C++ code, that should be easily understandable by everyone.

**Comment by nagasrihith608** [comment]
@siddharth25pandey, please assign this to me. Thank you

**Comment by siddharth25pandey** [comment]
> @siddharth25pandey, please assign this to me. Thank you

@siddharth25pandey Done 👍
